 # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

#  config.vm.box = "ubuntu/bionic64"
#  config.vm.box = "ubuntu/hirsute64"
  config.vm.box = "archlinux/archlinux"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "VAGRANT-archlinux"
     vb.cpus = "4"
     vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo pacman -Syyu --noconfirm
    sudo pacman --noconfirm -S base-devel curl git gcc-ada ncurses zlib
    #git clone https://review.coreboot.org/coreboot /source/coreboot
  SHELL
  config.vm.synced_folder "./source", "/source" 
end
 
