# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |vb|
#     vb.gui = true
     vb.name = "VAGRANT-CentOS8"
     vb.cpus = "4"
     vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL

    sudo dnf check-update
    sudo dnf update -y
    sudo dnf install epel-release -y
    sudo dnf groupinstall 'Development Tools' -y
    sudo dnf install python39 bison curl flex git gcc-gnat ncurses ncurses-devel m4 zlib zlib-devel -y
  SHELL
  config.vm.synced_folder "./source", "/source" 
end
