 # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

#  config.vm.box = "ubuntu/bionic64"
#  config.vm.box = "ubuntu/hirsute64"
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
#     vb.gui = true
#     vb.name = "ubuntu-hirsute64"
     vb.name = "VAGRANT-ubuntu-focal64"
     vb.cpus = "4"
     vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y upgrade    
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tmux python bison build-essential curl flex git gnat libncurses5-dev m4 zlib1g-dev
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y autoconf autopoint pkg-config freetype2-demos
    #git clone https://review.coreboot.org/coreboot /source/coreboot
  SHELL
  config.vm.synced_folder "./source", "/source" 
end
